server:
  port: 8080

spring:
  application:
    name: ecomkassa-catalog

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml

ecom-catalog:
  datasource:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_DBNAME:ecom_catalog}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}

logging:
  level:
    root: INFO
    org.springframework: WARN
    com.thepointmoscow.catalog: DEBUG